# vim: ft=yaml
---
driver:
  name: docker

provisioner:
  name: salt_solo
  formula: sensu
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - sensu

platforms:
  - name: debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        sensu.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - sensu
