# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      "*":
        - test.mockup
        - sensu

platforms:
  - name: bento/debian-8.6

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        sensu.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - sensu

